generalize the pip version extraction to be more robust
Signed-off-by: Brian Harring <ferringb@gmail.com>

diff --git a/test-revdep/action.yml b/test-revdep/action.yml
--- a/test-revdep/action.yml
+++ b/test-revdep/action.yml
@@ -44,7 +44,9 @@ runs:
       shell: bash
       run: |
         set -ex
-        echo LAST_RELEASE="v$(pip index versions "${{ inputs.target }}" | grep LATEST | grep -oP '[\d.]+')" >> $GITHUB_ENV
+        l=$(pip index versions "${{ inputs.target }}" > /dev/null | head -1 | sed -re 's/.*\(([^)]+)\).*$/\1/')
+        [ -z "$l" ] && { echo "couldn't find the version, failing out"; exit 1; }
+        echo LAST_RELEASE="v${l}" >> $GITHUB_ENV
 
     - name: Checkout ${{ inputs.target }} ${{ env.LAST_RELEASE != '' && env.LAST_RELEASE || '' }}
       uses: actions/checkout@v6
